### ISSUE TITLE
Cannot pull request & add Void Linux 

### ISSUE THREAD

**Issue by makimask-jx** [spookyorange/vscode-linux-install#1]
I want to pull a request to add Void Linux as a tested distro, but it does not work, maybe because of a skill issue
![CannotPullRequest](https://github.com/spookyorange/vscode-linux-install/assets/161981890/461e13ce-5776-440f-a9d2-29ee17fa6245)

**Comment by makimask-jx** [comment]
There is no more branches to use

**Comment by spookyorange** [comment]
Hello there! Did you try to open a PR from this repo to this repo, if so, can you please fork it and *from that fork*, PR it?
For more information you may research: "Creating a PR from a fork"
GitHub has a nice and short guide for it that I'd recommend*: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Happy hacking!

**Comment by makimask-jx** [comment]
That was a fast reply. I will research and try to the different links you provided me 

:D
