### ISSUE TITLE
Error: Installation failed  Ubuntu 23.10

### ISSUE THREAD

**Issue by makimask-jx** [spookyorange/vscode-linux-install#4]
If you execute the script in Ubuntu, it does not download vs code and returns a positive message as if the script worked 
Reproduce: Open a VM with Ubuntu, in the live system execute:

`sudo apt install git `
`git clone  https://github.com/spookyorange/vscode-linux-install.git`
`cd vscode-linux-install`
`sh ./install.sh`

Log attached 
![Screenshot 2024-05-05 171511](https://github.com/spookyorange/vscode-linux-install/assets/161981890/8968ccfb-2b3d-4616-a739-382d6b51db98)

**Comment by makimask-jx** [comment]
I think it should return an error clarifying you don't have curl, instead of proceeding and return "Installation is successful" even with the curl error above

**Comment by spookyorange** [comment]
Yeah, I see the problem, we should add prerequisites part to the README and return an error whenever a prerequisite is missing. Thank you very much for this information. Would you like to add that, or should I work on it?

Also we might need to add a check after tar installation, if it doesn't exist afterwards, we should give error and exit 1?

Let me know if you're interested in making it happen!

**Comment by makimask-jx** [comment]
I will pull a request for a modified script that checks for curl and also checks for the installation to be successful. After merging the curl one, I may start working on the installation error catching, outside curl. I am not familiar with bash scripting!

**Comment by spookyorange** [comment]
It'd be grand.
Thank you very much for your contributions, you rock!
